/* build-data.js — ports the smart-siddur prayer corpus into a single
 * self-contained JS file the Otzaria plugin can load via a <script> tag.
 *
 * Why a <script> file and not JSON+fetch: Otzaria loads the plugin from a
 * file:// origin where fetch() is blocked, so all data must be inlined as a
 * global (window.SIDDUR_DATA), exactly like the legacy data/texts.js.
 *
 * Source: ../smart-siddur/assets/prayers (manifest-indexed JSON segments +
 * templates) + Hebrew segment labels parsed out of the Flutter constants file.
 *
 * Run:  node tools/build-data.js
 * Out:  data/siddur-data.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SS = path.join(ROOT, 'smart-siddur');
const PRAYERS = path.join(SS, 'assets', 'prayers');
const MANIFEST = path.join(PRAYERS, '_manifest.json');
const LABELS_DART = path.join(SS, 'lib', 'presentation', 'constants', 'segment_labels.dart');
const OUT = path.join(ROOT, 'data', 'siddur-data.js');

function readJson(p) { return JSON.parse(fs.readFileSync(p, 'utf8')); }

// Resolve a manifest path (already repo-relative, e.g. "assets/prayers/..")
// against the smart-siddur root.
function resolveAsset(rel) { return path.join(SS, rel); }

const manifest = readJson(MANIFEST);

const out = {
  common: {},
  nusach: { ashkenaz: {}, sfard: {}, edot_mizrach: {} },
  templates: {},
  mappings: {},
  labels: {},
};

let counts = { common: 0, ashkenaz: 0, sfard: 0, edot_mizrach: 0, templates: 0, mappings: 0 };
const missing = [];

// ── common segments (and the mapping files that live under common) ──────────
for (const [id, rel] of Object.entries(manifest.common)) {
  const p = resolveAsset(rel);
  if (!fs.existsSync(p)) { missing.push(rel); continue; }
  const data = readJson(p);
  if (id.startsWith('_')) {            // _gra_ssy_mapping / _kriah_mon_thu_mapping
    out.mappings[id.replace(/^_/, '')] = data;
    counts.mappings++;
  } else {
    out.common[id] = data;
    counts.common++;
  }
}

// ── per-nusach segments ─────────────────────────────────────────────────────
for (const nusach of ['ashkenaz', 'sfard', 'edot_mizrach']) {
  const map = manifest.nusach[nusach] || {};
  for (const [id, rel] of Object.entries(map)) {
    const p = resolveAsset(rel);
    if (!fs.existsSync(p)) { missing.push(rel); continue; }
    out.nusach[nusach][id] = readJson(p);
    counts[nusach]++;
  }
}

// ── templates ───────────────────────────────────────────────────────────────
for (const [id, rel] of Object.entries(manifest.templates)) {
  const p = resolveAsset(rel);
  if (!fs.existsSync(p)) { missing.push(rel); continue; }
  out.templates[id] = readJson(p);
  counts.templates++;
}

// ── extra mapping files not indexed in manifest.common (omer, korbanot) ─────
// Glob for any "_*mapping*.json" or "_omer*.json" / "_sukkot*.json" under the
// prayers tree and bucket them by a normalised basename key.
function walk(dir, acc) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}
const allFiles = walk(PRAYERS, []);
for (const full of allFiles) {
  const base = path.basename(full);
  if (!/^_.*\.json$/.test(base)) continue;          // only "_*.json" data files
  if (base === '_manifest.json') continue;          // the index itself, not data
  const key = base.replace(/^_/, '').replace(/\.json$/, '');
  if (out.mappings[key]) continue;                  // already captured via manifest
  out.mappings[key] = readJson(full);
  counts.mappings++;
}

// ── segment labels (parse the Dart const map) ───────────────────────────────
{
  const src = fs.readFileSync(LABELS_DART, 'utf8');
  // Match  'key': 'value',  and  'key': "value",  (Hebrew values, may contain ")
  const re = /'([^']+)'\s*:\s*'((?:[^'\\]|\\.)*)'/g;
  let m, n = 0;
  while ((m = re.exec(src)) !== null) {
    out.labels[m[1]] = m[2];
    n++;
  }
  counts.labels = n;
}

// ── emit ─────────────────────────────────────────────────────────────────────
fs.mkdirSync(path.dirname(OUT), { recursive: true });
const header =
  '/* siddur-data.js — GENERATED by tools/build-data.js. Do not edit by hand.\n' +
  ' * Prayer corpus ported from smart-siddur (RefaelGamliel). Strictly Orthodox.\n' +
  ' */\n';
fs.writeFileSync(
  OUT,
  header + 'window.SIDDUR_DATA = ' + JSON.stringify(out) + ';\n',
  'utf8'
);

const bytes = fs.statSync(OUT).size;
console.log('Wrote', path.relative(ROOT, OUT), '(' + (bytes / 1024 / 1024).toFixed(2) + ' MB)');
console.log('counts:', JSON.stringify(counts));
console.log('mapping keys:', Object.keys(out.mappings).join(', '));
console.log('templates:', Object.keys(out.templates).length);
if (missing.length) console.log('MISSING (' + missing.length + '):', missing.slice(0, 10).join('\n  '));
