#!/usr/bin/env python3
"""extract-shabbat.py — extract Shabbat (and later Yom-Tov) services from the
Otzaria seforim.db into a tracked data file (data/shabbat-data.js).

The DB is a LOCAL source (not a build dependency), so we extract its text ONCE
into a committed JS data file — mirroring how data-overrides/ pin DB-sourced
corrections. Re-run only when refreshing from a newer DB.

Output: window.SIDURON_SHABBAT = { <nusach>: { <service>: [ {kind,text} ... ] } }
  kind: 'header' | 'instruction' | 'text'   (rendered by js/services.js)

Run: python3 tools/extract-shabbat.py [path-to-seforim.db]
"""
import sqlite3, json, re, sys, os

DB = sys.argv[1] if len(sys.argv) > 1 else '/Users/david/Downloads/otzaria_latest/otzaria/seforim.db'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'shabbat-data.js')

# Per-nusach config: which book, and each app-service → ordered list of DB
# section-prefixes (matched against heRef). Musaf folds into the shacharit tab.
CONFIG = {
    'edot_mizrach': {
        'book': 5777,
        'services': {
            'maariv':    ['קבלת שבת', 'ערבית של שבת'],
            'shacharit': ['שחרית של שבת', 'מוסף של שבת'],
            'mincha':    ['מנחה של שבת'],
        },
    },
    'sfard': {
        'book': 5775,   # סידור ספרד לשבת
        'services': {
            'maariv':    ['קבלת שבת', 'תפלת ערבית לשבת'],
            'shacharit': ['תפלת שחרית', 'תפלת מוסף'],
            'mincha':    ['מנחה לשבת'],
        },
    },
    'ashkenaz': {
        'book': 5780,   # סידור אשכנז → seder "שבת"
        'services': {
            'maariv':    ['שבת, קבלת שבת', 'שבת, מעריב'],
            'shacharit': ['שבת, שחרית', 'שבת, מוסף לשבת'],
            'mincha':    ['שבת, מנחה'],
        },
    },
}

def strip_tags(s, keep_bold=True):
    s = re.sub(r'</?big>', '', s)
    s = re.sub(r'</?small>', '', s)
    if not keep_bold:
        s = re.sub(r'</?b>', '', s)
    return re.sub(r'[ \t]+', ' ', s).strip()

def is_pure_rubric(s):
    # a line whose visible content lives entirely inside <small>…</small>
    if '<small>' not in s:
        return False
    without_small = re.sub(r'<small>.*?</small>', '', s, flags=re.S)
    return strip_tags(without_small, keep_bold=False) == ''

def line_to_seg(content):
    c = content.strip()
    if not c:
        return None
    if c.startswith('<big>'):
        return {'kind': 'header', 'text': strip_tags(c, keep_bold=False)}
    if is_pure_rubric(c):
        return {'kind': 'instruction', 'text': strip_tags(c, keep_bold=False)}
    return {'kind': 'text', 'text': strip_tags(c, keep_bold=True)}

def subsection(heref):
    # heRef = "book, sederA, sederB, …, <letter>"; return the component before the
    # trailing letter (the prayer/section name), or '' if none.
    parts = [p.strip() for p in (heref or '').split(',')]
    return parts[-2] if len(parts) >= 2 else ''

conn = sqlite3.connect('file:%s?mode=ro' % DB, uri=True)
out = {}
for nusach, cfg in CONFIG.items():
    book = cfg['book']
    out[nusach] = {}
    for svc, prefixes in cfg['services'].items():
        segs = []
        for prefix in prefixes:
            rows = conn.execute(
                "SELECT heRef, content FROM line WHERE bookId=? AND heRef LIKE ? ORDER BY lineIndex",
                (book, '%' + prefix + '%')).fetchall()
            last_sub = None
            for heref, content in rows:
                sub = subsection(heref)
                seg = line_to_seg(content)
                if seg is None:
                    continue
                # Insert a section header at each sub-section boundary, unless the
                # line itself already is a <big> header.
                if sub and sub != last_sub and seg['kind'] != 'header':
                    segs.append({'kind': 'header', 'text': sub})
                last_sub = sub
                segs.append(seg)
        out[nusach][svc] = segs

conn.close()
os.makedirs(os.path.dirname(OUT), exist_ok=True)
header = ('/* shabbat-data.js — GENERATED by tools/extract-shabbat.py from Otzaria\n'
          ' * seforim.db (authoritative). Shabbat/Yom-Tov services per nusach.\n'
          ' * Do not edit by hand; re-run the extractor to refresh. */\n')
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(header + 'window.SIDURON_SHABBAT = ' + json.dumps(out, ensure_ascii=False) + ';\n')

kb = os.path.getsize(OUT) / 1024
print('Wrote data/shabbat-data.js (%.0f KB)' % kb)
for nusach in out:
    for svc, segs in out[nusach].items():
        hdrs = [s['text'] for s in segs if s['kind'] == 'header']
        print('  %-13s %-10s segs=%-4d headers=%d' % (nusach, svc, len(segs), len(hdrs)))
